# Ecommerce Dataset Cleaning with Pandas

This notebook uses simple Pandas code to explore and clean an ecommerce dataset.

## 1. Import Pandas and Load the CSV File

In [1]:
import pandas as pd

# Load the CSV file into a DataFrame
input_file = "Ecommerce_extracted/Combined_dataset.csv"
df = pd.read_csv(input_file)

print("Dataset loaded successfully")

Dataset loaded successfully

## 2. Explore the Dataset

Here we look at the first rows, last rows, size of the dataset, columns, and data types.

In [2]:
# Show the first 5 rows
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [3]:
# Show the last 5 rows
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [4]:
# Check number of rows and columns
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 1000
Number of columns: 24

In [5]:
# Show all column names
print("Column names:")
for column in df.columns:
    print(column)

Column names:
product_id
title
product_description
rating
ratings_count
initial_price
discount
final_price
currency
images
delivery_options
product_details
breadcrumbs
product_specifications
amount_of_stars
what_customers_said
seller_name
sizes
videos
seller_information
variations
best_offer
more_offers
category

In [6]:
# Check data types of each column
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

## 3. Find Missing Values

In [7]:
# Check missing values in each column
missing_values = df.isnull().sum()
missing_values

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

## 4. Clean the Dataset

Cleaning steps used:

- Remove duplicate rows.
- Fill missing `discount` values with `0`.
- Fill missing text values with `Not Available`.
- Replace seller values that contain black block/redacted text with `Not Available`.
- Drop the `videos` column because most rows are missing that value.
- Convert `final_price` into a numeric `price` column.
- Add a `quantity` column because the dataset does not already have one.
- Create `total_amount = price * quantity`.

In [8]:
# Make a copy so the original DataFrame stays unchanged
df_clean = df.copy()

# Count duplicate rows before removing them
duplicate_count = df_clean.duplicated().sum()
print("Duplicate rows before cleaning:", duplicate_count)

# Remove duplicate rows
df_clean = df_clean.drop_duplicates()

print("Rows after removing duplicates:", df_clean.shape[0])

Duplicate rows before cleaning: 0

Rows after removing duplicates: 1000

In [9]:
# Fill missing discount values with 0
df_clean["discount"] = df_clean["discount"].fillna(0)

# Fill missing text values with a simple message
df_clean["what_customers_said"] = df_clean["what_customers_said"].fillna("Not Available")
df_clean["seller_name"] = df_clean["seller_name"].fillna("Not Available")
df_clean["seller_information"] = df_clean["seller_information"].fillna("Not Available")
df_clean["variations"] = df_clean["variations"].fillna("Not Available")

# Some seller names and seller addresses have black strips/redacted text.
# These values are not useful, so we replace them with Not Available.
black_block = chr(9608)

seller_name_hidden = df_clean["seller_name"].str.contains(black_block)
seller_info_hidden = df_clean["seller_information"].str.contains(black_block)

print("Seller names with black strips:", seller_name_hidden.sum())
print("Seller information with black strips:", seller_info_hidden.sum())

df_clean.loc[seller_name_hidden, "seller_name"] = "Not Available"
df_clean.loc[seller_info_hidden, "seller_information"] = "Not Available"

# Drop the videos column because many values are missing
df_clean = df_clean.drop("videos", axis=1)

print("Missing values and black strip values handled")

Seller names with black strips: 694
Seller information with black strips: 699
Missing values and black strip values handled

In [10]:
# Convert final_price from text into a number
# Example: currency symbol + 3,995.00 becomes 3995.00
df_clean["price"] = df_clean["final_price"].astype(str)

# Remove quote marks and commas first
df_clean["price"] = df_clean["price"].str.replace('"', "", regex=False)
df_clean["price"] = df_clean["price"].str.replace(",", "", regex=False)

# Remove the first character because it is the currency symbol
df_clean["price"] = df_clean["price"].str[1:]

# Change the cleaned price text into numbers
df_clean["price"] = df_clean["price"].astype(float)

# The dataset does not have a quantity column, so we use 1 for each product
df_clean["quantity"] = 1

# Create the derived total_amount column
df_clean["total_amount"] = df_clean["price"] * df_clean["quantity"]

df_clean[["final_price", "price", "quantity", "total_amount"]].head()

   final_price   price  quantity  total_amount
0  "₹3,995.00"  3995.0         1        3995.0
1  "₹2,899.00"  2899.0         1        2899.0
2  "₹2,999.00"  2999.0         1        2999.0
3  "₹1,675.00"  1675.0         1        1675.0
4  "₹2,899.00"  2899.0         1        2899.0

## 4b. Clean and Expand Rating Details (amount_of_stars)

The amount_of_stars column has a dictionary string in it. I am using json_normalize to expand it out into separate columns.

In [11]:
# The amount_of_stars column contains text in JSON format
# This is hard to analyze, so we convert it to separate numeric columns using json.loads
import json
stars_df = pd.json_normalize(df_clean["amount_of_stars"].apply(json.loads))

# Reset index to safely concatenate columns side-by-side
df_clean = df_clean.reset_index(drop=True)
df_clean = pd.concat([df_clean, stars_df], axis=1)

# Show a preview of the newly expanded star columns alongside the original column
df_clean[["amount_of_stars", "1_star", "2_stars", "3_stars", "4_stars", "5_stars"]].head()

,amount_of_stars,1_star,2_stars,3_stars,4_stars,5_stars
0,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",2,0,3,4,6
1,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",3,4,2,8,50
2,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",9,5,10,55,147
3,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",33,21,69,282,647
4,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,0,0,4,8

## 4c. Clean and Expand Product Details (product_details)

The product_details column has json strings. I am splitting them out into separate columns for description, material_and_care, and size_and_fit.

In [12]:
# Parse product_details JSON keys into separate text columns
details_df = pd.json_normalize(df_clean["product_details"].apply(json.loads))

# Fill any missing values in the expanded details with 'Not Available'
details_df = details_df.fillna("Not Available")

# Concatenate these new detail columns to our main DataFrame
df_clean = pd.concat([df_clean, details_df], axis=1)

# Show a preview of the original product_details and the newly extracted columns
df_clean[["product_details", "description", "material_and_care", "size_and_fit"]].head()

,product_details,description,material_and_care,size_and_fit
0,"{""description"":""Navy Blue solid backpackNon-Pa...",Navy Blue solid backpackNon-Padded haul loop1 ...,"Synthetic Leather. Wipe with a clean, dry clot...",Height: 34 cm. Width: 33 cm. Depth: 14 cm. Vol...
1,"{""description"":""Navy Blue backpackNon-Padded h...",Navy Blue backpackNon-Padded haul loop1 main c...,"Polyester. Wipe with a clean, dry cloth to rem...",Height: 47 cm. Width: 31 cm. Depth: 14 cm. Lap...
2,"{""description"":""Pink solid backpacks Non-padd...",Pink solid backpacks Non-padded sternum shoul...,Material: Synthetic. Wipe with a damp cloth,Dimensions:&nbsp;28.5 X 23.5 X 11 cm. Volume: ...
3,"{""description"":""Navy and grey printed backpack...","Navy and grey printed backpackOne haul loop, t...","Polyester. Wipe with a clean, dry cloth when n...",Height: 45 cm. Width: 31 cm. Depth: 20 cm
4,"{""description"":""Blue solid bath robe, has a sh...","Blue solid bath robe, has a shawl collar with ...",Terry cotton. Warm machine-wash. Wash separate...,The model (height (6') is wearing size M

In [13]:
# Check missing values again after cleaning
df_clean.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
price                     0
quantity                  0
total_amount              0
1_star                    0
2_stars                   0
3_stars                   0
4_stars                   0
5_stars                   0
description               0
material_and_care         0
size_and_fit              0
dtype: int64

## 5. Basic Data Operations

In [14]:
# Filter rows where rating is 4.0 or higher
high_rated_products = df_clean[df_clean["rating"] >= 4.0]

high_rated_products.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,quantity,total_amount,1_star,2_stars,3_stars,4_stars,5_stars,description,material_and_care,size_and_fit
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,1,2899.0,3,4,2,8,50,Navy Blue backpackNon-Padded haul loop1 main c...,"Polyester. Wipe with a clean, dry cloth to rem...",Height: 47 cm. Width: 31 cm. Depth: 14 cm. Lap...
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,1,2999.0,9,5,10,55,147,Pink solid backpacks Non-padded sternum shoul...,Material: Synthetic. Wipe with a damp cloth,Dimensions:&nbsp;28.5 X 23.5 X 11 cm. Volume: ...
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,1,1675.0,33,21,69,282,647,"Navy and grey printed backpackOne haul loop, t...","Polyester. Wipe with a clean, dry cloth when n...",Height: 45 cm. Width: 31 cm. Depth: 20 cm
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,1,2899.0,0,0,0,4,8,"Blue solid bath robe, has a shawl collar with ...",Terry cotton. Warm machine-wash. Wash separate...,The model (height (6') is wearing size M
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,0.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,1,1399.0,2,2,0,5,33,Soap dispenser in glazed stoneware with a plas...,100% Stoneware. Wipe with a damp cloth to remo...,Dimension:. Diameter 8 cm.. Height excluding p...

In [15]:
# Select only a few useful columns
selected_columns = ["product_id", "title", "category", "price", "quantity", "total_amount", "rating", "5_stars", "description"]

small_table = df_clean[selected_columns]
small_table.head()

,product_id,title,category,price,quantity,total_amount,rating,5_stars,description
0,8376765,Lino Perros,backpacks,3995.0,1,3995.0,3.8,6,Navy Blue solid backpackNon-Padded haul loop1 ...
1,9136281,Tommy Hilfiger,backpacks,2899.0,1,2899.0,4.5,50,Navy Blue backpackNon-Padded haul loop1 main c...
2,17633752,Lavie,backpacks,2999.0,1,2999.0,4.4,147,Pink solid backpacks Non-padded sternum shoul...
3,1376949,F Gear,backpacks,1675.0,1,1675.0,4.4,647,"Navy and grey printed backpackOne haul loop, t..."
4,13939916,MYTRIDENT,bath-robe,2899.0,1,2899.0,4.7,8,"Blue solid bath robe, has a shawl collar with ..."

## 6. Save the Cleaned Dataset

In [16]:
# Save the cleaned data into a new CSV file
output_file = "ecommerce_cleaned.csv"
df_clean.to_csv(output_file, index=False)

print("Cleaned dataset saved as", output_file)

Cleaned dataset saved as ecommerce_cleaned.csv

## 7. Brief Summary

The ecommerce dataset was loaded and explored using Pandas. Missing values were identified and handled, duplicate rows were removed, useful rows and columns were selected, and a new `total_amount` column was created. The final cleaned dataset was saved as `ecommerce_cleaned.csv`.